### ISSUE TITLE
Borland C++ 3.1: emm386c.asm line 414 Error: Invalid combination of opcode and operands in function xmscall

### ISSUE THREAD

**Issue by El-Virus** [FDOS/emm386-himem#1]
Hello, I was trying to compile emm386.exe with Borlandc 3.1 but I get an error at line 414: Invalid combination of opcode and operands in function xmscall. the error comes from "asm mov ah,function" (BTW: neither doesn't work on the xmscall32 I've tried it).
Can someone help me?
Thanks in advance.

**Comment by andrewbird** [comment]
It looks like you need to patch the source before trying to build. There's a [readme](https://github.com/FDOS/emm386/blob/master/build/readme) that describes this. @PerditionC is there any reason why this patch is not already applied to the repository and the step removed?

**Comment by El-Virus** [comment]
@andrewbird Running the command specified on the readme file gives the following output:
Error: Unable to open patch file (-fZp1) for reading
Am I missing something, maybe running the incorrect version of borlandc? I'm running 3.1
Thanks for your help so far.

**Comment by andrewbird** [comment]
I applied the patch (mostly) to my branch https://github.com/andrewbird/emm386/tree/dopatch but as yet it's untested. Feel free to check it out and test yourself.

**Comment by El-Virus** [comment]
Thanks, Andrew, I'll test it right now.

**Comment by El-Virus** [comment]
@andrewbird It compiled without any problem. BTW I have a question, does emm386 work with himem.sys or do I have to use himem.exe? Thanks.

**Comment by andrewbird** [comment]
Sorry @El-Virus I'm not really the man to ask about this, my proper DOS use is so long ago. These days I only fiddle with it as I help out on https://github.com/dosemu2/dosemu2 Perhaps someone on .https://sourceforge.net/p/freedos/mailman/freedos-user/ can help out?

**Comment by El-Virus** [comment]
Ok, thanks Andrew.
